language: go
sudo: required
before_install:
  - sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable -y
  - sudo apt-get update -q
  - sudo apt-get dist-upgrade -y
  - sudo apt-get install lxd -y
  - go get -u github.com/golang/dep/...
install: dep ensure
